---

broker_mobile_configuration:
- section: openshift
  name: image_pull_policy
  value: Always
- section: openshift
  name: sandbox_role
  value: admin
- section: broker
  name: launch_apb_on_bind
  value: true

#The url for the registry that hosts our APB images
ansible_playbookbundle_registry_url: https://registry.hub.docker.com

#The organisation that our APB images are in
ansible_playbook_bundle_registry_org: aerogearcatalog
